### 
POST http://localhost:8080/api/role HTTP/1.1
content-type: application/json

{
    "role_name": "admin2",
    "remark": "管理员2",
    "display_name": "管理员2"
}
### 
PUT http://localhost:8080/api/role/update HTTP/1.1
content-type: application/json

{
    "role_name": "test2",
    "remark": "角色信息修改测试",
    "id": "753968567103524864",
    "display_name": "测试角色"

}
### 

DELETE  http://localhost:8080/api/role/delete/753968567103524864 HTTP/1.1
content-type: application/json

### 
GET   http://localhost:8080/api/role/all HTTP/1.1
content-type: application/json

### 
GET   http://localhost:8080/api/role/user/753979508838895616 HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDAwODQwMDYsImlhdCI6MTYwMDA2NjAwNiwiaXNzIjoibGxoIiwicm9sZXMiOlsiYWRtaW4iXSwic3ViIjoiNzUzOTc5NTA4ODM4ODk1NjE2In0.peGGsFBsYNvbY6UKFBj4cvBd-HCOx7R5UaY-Ryqlrmg


### 